### ISSUE TITLE
QIR-Runner appears not to work on both Ubuntu 20.04 and Ubuntu 22.04

### ISSUE THREAD

**Issue by wongey** [qir-alliance/qir-runner#74]
I have two versions of Ubuntu: 20.04 on a server somewhere and 22.04 on my local computer. In both places, I downloaded the the newest release [qir-runner-0.3.0-ubuntu-20.04-amd64.zip](https://github.com/qir-alliance/qir-runner/releases/download/v0.3.0/qir-runner-0.3.0-ubuntu-20.04-amd64.zip) from [https://github.com/qir-alliance/qir-runner/releases](https://github.com/qir-alliance/qir-runner/releases) and unzipped the file in my home folder.

I then used pyqir to convert some [examples](https://github.com/qir-alliance/pyqir/tree/main/examples) into QIR format as an *.ll file. Then I tried to run commands:
qir-runner -f filename.ll
./qir-runner -f filename.ll
on both operating systems and the error was "command not found" in each case. I also tried as sudo with the same results.

Note: I had already sent a version of this message to Stefan in a private conversation and it was suggested that I post my issue here. @swernli: Update for you since your last message to me - I have 22.04 on my local computer and tried the same thing and I got the same error.

**Comment by swernli** [comment]
Thanks for filing the issue for visibility! I was wrong before because I got my version numbers mixed up; I thought the repo had been updated to build with Ubuntu 22.04 but actually still builds with 20.04. I'm working on a PR to add 22.04 to the build, so once that produces an artifact you can try out that binary.

For the specific error of "command not found" I think it may be an issue of permissions on the file. I tried out the Ubuntu 20.04 artifact in a codespace running the matching OS and was able to get it working with the following commands:

```
wget https://github.com/qir-alliance/qir-runner/releases/download/v0.3.0/qir-runner-0.3.0-ubuntu-20.04-amd64.zip

unzip ./qir-runner-0.3.0-ubuntu-20.04-amd64.zip

chmod +x ./qir-runner

./qir-runner —help
```

Of note, I did see the "command not found" error before I used `chmod` to add execute permissions to the file, so make sure you do that before trying to use the unzipped binary (you may need to add `sudo` to the `chmod` depending on your local settings). It's still possible my container environment has some dependency installed in it that your environment doesn't have, so let me know if that does not resolve the issue and we can try to diagnose further.

**Comment by swernli** [comment]
A new build with Ubuntu 22.04 completed with artifact here: https://github.com/qir-alliance/qir-runner/suites/13512271172/artifacts/742652691
Give that a try too and see if that works on your system!

**Comment by wongey** [comment]
Thank you very much for your rapid troubleshooting! I can report that changing the permissions as you instructed above worked on Ubuntu 22.04 with the qir-runner-0.3.0-ubuntu-20.04-mod64 version. Your new build also worked (with the permission change). As I believe my problem has been addressed, I will close this issue. Hope it will be helpful for others in the future!
